# This is a basebox compose file
# There should be 1 file per website
# It is built in such a way that you can spin this up develop and then spin down


# https://docs.docker.com/compose/compose-file
version: "3.6"

# https://docs.docker.com/compose/compose-file/#service-configuration-reference
services:

  #custom name
  apache:
      tty: true

      # https://docs.docker.com/compose/compose-file/#image
      # https://github.com/udovicic/echo => https://hub.docker.com/r/udovicic/echo/
      image: cschrum/onebox-base:7.0

      # https://docs.docker.com/compose/compose-file/#ports
      ports:
          - "80:80"
          - "443:443"

      # https://docs.docker.com/compose/compose-file/#expose
      expose:
          - "9000"

      # https://docs.docker.com/compose/compose-file/#volumes
      volumes:
          - ~/.composer:/var/www/.composer
          - ~/.npm:/var/www/.npm
          - ./docker/services/apache/sites-available/${SERVER_NAME}.conf:/etc/apache2/sites-available/${SERVER_NAME}.conf
          - ./docker/services/apache/sites-available/${SERVER_NAME}.conf:/etc/apache2/sites-enabled/${SERVER_NAME}.conf
          - ./docker/services/apache/${SERVER_NAME}.crt:/etc/apache2/ssl/${SERVER_NAME}.crt
          - ./docker/services/apache/${SERVER_NAME}.key:/etc/apache2/ssl/${SERVER_NAME}.key
          - ./docker/services/magento/env.php.sample:/var/www/html/app/etc/env.php
          - ./src:/var/www/html:cached   

      # https://docs.docker.com/compose/compose-file/#environment
      environment:
          - TERM=xterm-256color
          - APACHE_RUN_USER=1000

      # https://docs.docker.com/compose/compose-file/#network-configuration-reference
      networks:
          default:
              aliases:
                  - ${SERVER_NAME}
                  - ${SERVER_ALIAS}

  db:

      # https://hub.docker.com/_/mysql/
      image: mysql:5.6

      ports:
        - 3300:3306
          
      volumes:
          - ./docker/services/mysql/data:/var/lib/mysql
          - ./docker/services/mysql/conf.d:/etc/mysql/conf.d

      # https://docs.docker.com/compose/compose-file/#healthcheck
      healthcheck:
          test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_USER} --execute \"SHOW DATABASES;\""
          interval: 3s
          timeout: 1s
          retries: 5

      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD} 

  redis:

      # https://hub.docker.com/_/redis/
      image: redis:latest

  mailhog:

      # https://hub.docker.com/r/mailhog/mailhog/
      image: mailhog/mailhog

      ports:
        - "1025:1025"
        - "8025:8025"       

  redis-session:
    image: redis
    ports:
     - 6379      
